version: '3'
services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: "production_nginx_container"
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./app/local-cdn:/local-cdn
    networks:
      - android-appium-network
  app:
    image: app
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: "production_app_container"
    entrypoint: ./docker-entrypoint.sh
    expose:
      - 8000:8000
    command: sh -c "cd /app/src && gunicorn --reload core.wsgi --bind 0.0.0.0:8000 --workers 4 --threads 4 --timeout 120"
    networks:
      - android-appium-network
    env_file:
      - "./app/.env"
    volumes:
      # - ./app/src:/app/src
      - ./app/logs:/logs
      - ./app/src:/app/src
      - ./app/local-cdn:/app/local-cdn
      - ./app/screenshots:/app/screenshots
      - ./app/apks:/app/apks
  android-emulator:
    image: budtmo/docker-android:emulator_11.0
    container_name: android-container
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S10
      - WEB_VNC=true
    devices:
      - /dev/kvm:/dev/kvm
    ports:
      - "6080:6080"
    networks:
      - android-appium-network

  appium-server:
    build: ./appium
    container_name: appium-server
    ports:
      - "4723:4723"
    networks:
      - android-appium-network

networks:
  android-appium-network:
    driver: bridge
