# Generated by Django 5.0.8 on 2024-08-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app", models.CharField(max_length=50)),
                ("feeder", models.CharField(max_length=50)),
                ("last_fed", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
