# Generated by Django 5.0.8 on 2024-08-11 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0002_feedings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedings",
            name="app",
        ),
    ]
