# Generated by Django 5.0.8 on 2024-08-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0003_remove_feedings_app"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedings",
            name="app",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
